#theme: jekyll-theme-cayman
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
title: "FLARE: The Workflow Orchestration Tool"
description: "FLARE: The Workflow Orchestration Tool"
sidebar:
  - home
  - getting-started
  - cli
  - label: Workflows
    children:
      - fccanalyses
      - mcproduction
      - fastsim
      - fullsim
  - citation

#search_enabled: true
auto_page_title: true
