#theme: jekyll-theme-cayman
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
title: FLARE
description: "FLARE : FCCee b2Luigi Automated Reconstruction And Event processing"
sidebar:
  - label: Workflows
    children:
      - fccanalyses-workflow
